name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create directory
      run: |
        mkdir bin

    - name: Build and test
      run: |
        gcc -o bin/program main.c
        ./bin/program
